AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  This template provisions the MlOps Orchestration workflow and Experiment Management Framework for the MlOPS-as-a-Service Solution.

Parameters:

  EmailAddress:
    Description: E-Mail Address to send deployment updates to.
    Type: String

  GitToken:
    NoEcho: 'true'
    Description: zipdl method only. Personal access token, needed for GitHub Enterprise and GitLab
    Type: String
    Default: ''

  S3BootstrapBucket:
    Description: >
      Name of the S3 Bucket for bootstratpping training asets
    Type: String

Resources:

  SNSTopic:
    Type: AWS::SNS::Topic
    Description: Deployment status messages.
    Properties:
      DisplayName: Machine Learning Ochestration Update Message
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
      TopicName: !Sub ${AWS::StackName}-SNS

  S3ExperimentBucket:
    Type: AWS::S3::Bucket
    Description: Training experiment data.
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${AWS::StackName}-training-experiments-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled

  PreConfig:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BootstrapBucket}/templates/pre-config-template.yaml
      Parameters:
        S3BootstrapBucket: !Ref S3BootstrapBucket
        S3ExperimentBucket: !Ref S3ExperimentBucket

  Webhook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BootstrapBucket}/templates/webhook-template.yaml
      Parameters:
        GitToken: !Ref GitToken
        QSS3BucketName: !Ref S3BootstrapBucket
        OutputBucket: !Ref S3ExperimentBucket

  SageMakerMlOps:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BootstrapBucket}/templates/sm-mlops-template.yaml
      Parameters:
       S3BootstrapBucket: !Ref S3BootstrapBucket
       SNSTopic: !Ref SNSTopic
       S3ExperimentBucket: !Ref S3ExperimentBucket
       MasterImage: !GetAtt PreConfig.Outputs.MasterImage

  PostConfig:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BootstrapBucket}/templates/post-config-template.yaml
      Parameters:
        S3BootstrapBucket: !Ref S3BootstrapBucket
        S3ExperimentBucket: !Ref S3ExperimentBucket
        SageMakerStateMachine: !GetAtt SageMakerMlOps.Outputs.SageMakerStateMachine

Outputs:

  ExperimentBucket:
    Description: S3 Bucekt container ML Experiment data.
    Value: !Ref S3ExperimentBucket

  WebHookApi:
    Description: GitHub Webhook endpoint.
    Value: !GetAtt Webhook.Outputs.ZipDownloadWebHookApi